# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\ajouter_emprunt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1139, 873)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setStyleSheet("background-color: rgb(31, 53, 61);\n"
"color : rgb(255, 255, 255);\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(20)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(40, 11, 50, 11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.reference = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        self.reference.setFont(font)
        self.reference.setStyleSheet("QLineEdit {\n"
"    border :2px solid ;\n"
"    border-radius : 15px;\n"
"    border-color: rgb(197, 181, 61);\n"
"    background-color: rgb(255, 255, 255);\n"
"    color :rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border : 2px solid rgbrgb(97, 89, 30);\n"
"}\n"
"\n"
"")
        self.reference.setMaxLength(3)
        self.reference.setObjectName("reference")
        self.horizontalLayout.addWidget(self.reference)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.widget = QtWidgets.QWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(40, -1, 50, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.num_insc = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        self.num_insc.setFont(font)
        self.num_insc.setStyleSheet("QLineEdit {\n"
"    border :2px solid ;\n"
"    border-radius : 15px;\n"
"    border-color: rgb(197, 181, 61);\n"
"    background-color: rgb(255, 255, 255);\n"
"    color :rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border : 2px solid rgbrgb(97, 89, 30);\n"
"}\n"
"\n"
"")
        self.num_insc.setObjectName("num_insc")
        self.horizontalLayout_2.addWidget(self.num_insc)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(217, 0, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.widget)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setContentsMargins(200, -1, 200, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    height : 35px;\n"
"    background-color :rgb(0, 71, 104);\n"
"    border-radius : 15px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_11.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setStyleSheet("color: rgb(220, 0, 0);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.widget_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", " Ajouter Un Emprunt"))
        self.label_2.setText(_translate("Form", "Référence De Livre"))
        self.label_3.setText(_translate("Form", "Numéro D\'inscription"))
        self.num_insc.setInputMask(_translate("Form", "999999"))
        self.pushButton.setText(_translate("Form", "Ajouter"))
import etudiant
